version: '3.1'

services:

  web:
    image: php:7.4-apache
    container_name: lamp-web
    volumes:
      - ./lamp-app:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lamp-db
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./lamp-db:/docker-entrypoint-initdb.d
